//Es el nucloe funcional de nuestra app
//async/await -->Limpia mls datos resividos de la API para bloquear ataques xss y encripta la lista en el dispositivo por medio de una API 
 const pokemonInput = document.getElementById("pokemonInput");
 const buscarBtn = document.getElementById("buscarBtn");
 const aleatorioBtn = document.getElementById("aleatorioBtn");
 const resultado = document.getElementById("resultado");


 // BUSCAR POKÉMON

 async function buscarPokemon(nombre) {

     if (!nombre) {
             resultado.innerHTML = `
                         <h2>Escribe un Pokémon</h2>
                                     <p>Ingresa un nombre o número.</p>
                                             `;
                                                     return;
                                                         }

                                                             resultado.innerHTML = `
                                                                     <h2>Buscando...</h2>
                                                                             <p>Espera un momento.</p>
                                                                                 `;

                                                                                     try {

                                                                                             const respuesta = await fetch(
                                                                                                         `https://pokeapi.co/api/v2/pokemon/${nombre.toLowerCase()}`
                                                                                                                 );

                                                                                                                         if (!respuesta.ok) {
                                                                                                                                     throw new Error("No encontrado");
                                                                                                                                             }

                                                                                                                                                     const pokemon = await respuesta.json();

                                                                                                                                                             const nombrePokemon =
                                                                                                                                                                         pokemon.name.charAt(0).toUpperCase() +
                                                                                                                                                                                     pokemon.name.slice(1);

                                                                                                                                                                                             resultado.innerHTML = `

                                                                                                                                                                                                         <img
                                                                                                                                                                                                                         src="${pokemon.sprites.other["official-artwork"].front_default}"
                                                                                                                                                                                                                                         alt="${nombrePokemon}"
                                                                                                                                                                                                                                                     >

                                                                                                                                                                                                                                                                 <h3>${nombrePokemon}</h3>

                                                                                                                                                                                                                                                                             <div class="datos">

                                                                                                                                                                                                                                                                                             <p><strong>ID:</strong> #${pokemon.id}</p>

                                                                                                                                                                                                                                                                                                             <p>
                                                                                                                                                                                                                                                                                                                                 <strong>Altura:</strong>
                                                                                                                                                                                                                                                                                                                                                     ${pokemon.height / 10} m
                                                                                                                                                                                                                                                                                                                                                                     </p>

                                                                                                                                                                                                                                                                                                                                                                                     <p>
                                                                                                                                                                                                                                                                                                                                                                                                         <strong>Peso:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                             ${pokemon.weight / 10} kg
                                                                                                                                                                                                                                                                                                                                                                                                                                             </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 `;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                             resultado.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <h2>Pokémon no encontrado</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Comprueba el nombre o número e inténtalo nuevamente.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // BOTÓN BUSCAR

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             buscarBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 buscarPokemon(pokemonInput.value.trim());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // BUSCAR CON ENTER

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 pokemonInput.addEventListener("keydown", (event) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (event.key === "Enter") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             buscarPokemon(pokemonInput.value.trim());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // POKÉMON ALEATORIO

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 aleatorioBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const numero = Math.floor(Math.random() * 1025) + 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         buscarPokemon(numero);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // ÁREA SEGURA

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const autenticarBtn =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             document.getElementById("autenticarBtn");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const pinInput =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 document.getElementById("pinInput");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const mensaje =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     document.getElementById("mensaje");


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     autenticarBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const pin = pinInput.value;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (!/^\d{4}$/.test(pin)) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     mensaje.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "El PIN debe tener exactamente 4 números.";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // PIN de ejemplo

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (pin === "1234") {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             mensaje.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "✅ Autenticación correcta.";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     mensaje.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "❌ PIN incorrecto.";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });
      // REGISTRAR PWA

      if ("serviceWorker" in navigator) {

          window.addEventListener("load", () => {

                  navigator.serviceWorker
                              .register("./sw.js")
                                          .then(() => {
                                                          console.log("PWA instalada correctamente");
                                                                      })
                                                                                  .catch((error) => {
                                                                                                  console.log("Error:", error);
                                                                                                              });

                                                                                                                  });

                                                                                                                  }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               